apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
  annotations:
    ${AWS_CONTROLLER_IAM_ROLE/#arn/eks.amazonaws.com/role-arn: arn}
