# The following patch adds a label of move-hierarchy for global identity resources like AWSClusterControllerIdentity
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: ""
  name: awsclustercontrolleridentities.infrastructure.cluster.x-k8s.io
